vaco-algo/vaco-algo-study

problems/[221206] 328. Odd Even Linked List.js, problems/[221208] 1710. Maximum Units on a Truck.js
물건 적재량이 많은 박스 순서 정보가 필요해서 sort 를 이용했습니다.
sort 메서드는 기존 배열을 바꾸므로 복사를 해준뒤 sort를 해서 순수함수가 되도록 했습니다.
그 후 가장 큰 적재량을 가진 박스부터 하나씩 가져와서 현재 남은 `truckSize` 와 비교해서 답을 구하는 로직입니다.
트럭에 남은 공간이 전혀 없거나 실을 박스들이 남아있지 않으면 끝이므로 while 문의 조건에 `truckSize && sortedBoxTypes.length` 를 넣어줬습니다.
`currentBox` 를 가져올땐 시간복잡도를 줄이기 위해 내림차순으로 정렬한 후 `shift` 가 아닌 오름차순으로 정렬한 후 `pop` 을 사용했습니다.
시간복잡도는 자바스크립트 내장 솔트함수를 사용했으므로 O(NlogN),
공간복잡도는 순수함수로 만들지 않았었다고 가정하면 인풋과 관계없이 고정된 변수만 사용하므로 O(1) 입니다.
탐욕 알고리즘 카테고리의 문제였는데 탐욕 알고리즘을 어떻게 적용해야 할지를 몰라 일단 생각나는 대로 풀었습니다.
=> [2022.12.08] 길지문

problems/[221209] 2078. Two Furthest Houses With Different Colors.js, problems/[221211] 561. Array Partition.js
오름차순으로 sort 해준 후 2의 배수 index를 가진 숫자들을 합해주는 식으로 풀었습니다.
=> [2022.12.11] 임현정

README.md
- 은혜님이 정리해주신 공간 복잡도 계산 방법 추가했습니다. 
- 저 이외의 다른 분들도 readme 업데이트 할 수 있게 정리해보았습니다.
<docs/readme 브랜치를 만든 적이 없는 경우>
1. 본인 fork 레포지토리 터미널로 가기.
2. `git checkout -b docs/readme` (docs/readme라는 브랜치를 만듭니다.)
3. `git reset b13ede831e69999878a4801783fd391ebdd9cff2` (제일 처음의 commit으로 모든 커밋을 리셋합니다. 이 과정을 하지 않으면 본인의 모든 커밋 내역이 함께 pr로 올라가게 됩니다.)
4. `git add .`
5. `git stash` (변경된 사항들을 stash에 넣어놓고 stage를 비웁니다.)
6. `git rebase algo/docs/readme`
7. `git stash drop` (5번에서 저장한 stash 파일은 필요없으므로 제거해주는 과정입니다.)
8. readme 파일 변경 후 변경한 readme 파일 커밋 (변경된 파일은 readme 파일만 있어야 합니다.)
9. `git push origin docs/readme` (본인 fork한 레포지토리로 git push)
10. 본인 레포지토리가 아닌 본래 레포지토리의 docs/readme 브랜치로 pr 올리기
<docs/readme 브랜치를 가지고 있는 경우>
1. git rebase algo/docs/readme
=> [readme] Add time complexity

problems/[221215] 1328. Break a Palindrome.js
정규식을 이용해서 a가 아닌 값을 먼저 a로 바꿔주었습니다. 모든 값이 'a'가 됐을 경우 다시 palindrome값이 되기 때문에 조건문을 이용해서 원래 문자인 palindrome 문자열 끝에서부터 a인 값을 'b'로 바꿔주고 break 해주었습니다.
- 시간 복잡도 : On
- 공간 복잡도 : O1
=> [2022.12.15] 임현정

README.md
=> [readme] 1215 문제 주소 추가

problems/[221209] 2078. Two Furthest Houses With Different Colors.js
포인터 두개를 사용하여 먼저 하나를 맨앞에 고정된 채 뒤에서부터 다른 값들을 찾았고, 그 다음엔 맨뒤에 하나 고정하고 앞에서부터 순환하여 다른 값들을 찾음.
- 시간 복잡도 : O(N)
=> Solve [221209] probelm on 221218 date

problems/[221215] 1328. Break a Palindrome.js
결국 실질적으로 로직에 사용하게 될 문자는 `a` 와 `b` 뿐이란 걸 깨달았습니다. 또 어차피 앞뒤가 똑같은 palindrome 이므로 문자열 길이의 반만 요소 검사를 하면 됐었고, 길이가 홀수일때 가운데 문자는 바꿔도 palindrome 을 깰 수 없으므로 가운데 요소 바로 앞 요소까지만 순환 시키는 로직으로 풀었습니다.
- 시간 복잡도 : O(N)
=> [2022.12.15] 길지문 (22.12.18에 품)

problems/[221215] 1328. Break a Palindrome.js, problems/[221217] 88. Merge Sorted Array.js
- 문제를 잘못 이해해서 제한 시간 내에 다 통과하지 못했습니다.
- 처음에 값을 return 하는 줄로만 알고 그렇게 풀었다가, 아니라는 것을 깨닫고 문제를 수정하였습니다.
<br>
- `nums1`에 `nums2`의 `n`길이 배열을 `m + i` 부터 할당해 하나의 배열을 만들어주었습니다.
- 그 다음 `nums1`에서 내부적으로 투 포인터를 이용해 sort해나가려고 했습니다.
- 왼쪽 포인터는 `0`, 오른쪽 포인터는 `m`부터 시작해 왼쪽이 작으면 넘어가고, 오른쪽이 작으면 왼쪽과 바꾸어주는 동작을 했는데요.
- 그러면 우측 배열에 정렬이 되지 않은 상태로 투포인터가 끝나서, 우측 배열을 정렬된 상태로 할당하던지 투 포인터를 다르게 써봐야 할 것 같습니다.
- 문제 해결 완료하였습니다.
- 2차적으로 접근한 내용은, 아예 새로운 배열을 만들어주는 것입니다.
- nums1의 m개의 배열, nums2의 n개의 배열을 통해 mergedArray라는 새로운 배열을 만들어주었습니다.
- mergedArray 내부에서 투 포인터를 동작시켜 nums1을 변경시킵니다.
- left의 값과 m이 만나거나(왼쪽 배열 초과), right가 mergerdArray의 길이를 넘기면(오른쪽 배열 초과) 나머지를 다 nums1에 할당하는 것으로 해결하였습니다.
- 시간 복잡도는 O(n), 공간복잡도는 …
=> [2022.12.17] 공재혁

problems/[221217] 88. Merge Sorted Array.js, problems/[221220] 1971. Find if Path Exists in Graph.js
재귀를 이용해서, `destination`과 연결되면 `true`가 반환되도록 하였습니다.
주어진 `edges`에서 해당 node와 연결된 `relations`라는 배열을 만들고, 
`relations`에 `destination`이 있다면 `true`를 반환, 아니라면 순회를 돌도록 하였는데요.
그래프 특성상 뻗어나가는 경우의 수가 너무 많다보니 시간초과 에러가 나서 실패하였습니다.
나름의 최적화를 위해서 한 번 거쳐간 node는 filter로 제외했음에도, 경우의 수가 너무 많았던게 아닌가 싶습니다.
거쳐간 node의 숫자의 제한을 두면 어떨까? 싶어 early return을 둬봤지만 해결되지 못하였습니다.
재귀를 이용한 그래프문제라 시간복잡도 공간복잡도가 어떻게 될 지 감이 잘 잡히지 않네요..
조금 더 공부해보고 작성하겠습니다.
- 시간 복잡도 : 
- 공간 복잡도 :
추가로 접근해서 문제를 해결하였습니다. 도움을 주신 은혜님 감사해여...!
Set을 이용한 큐로 해결하였습니다. 큐에는 현재 `source`를 담고, 큐에 있는 아이템들을 하나하나씩 순회하는 형식입니다.
`source`와 연결되어있는 vertex들이 큐에 추가되고, 최종적으로 큐에는 `source`에서 접근 가능한 모든 vertex가 쌓이게 됩니다.
연결된 vertex 중 `destination`이 있다면 `true`를 반환하고, 큐를 다 순회해도 …
=> [2022.12.20] 공재혁

problems/[221208] 1710. Maximum Units on a Truck.js, problems/[221220] 1971. Find if Path Exists in Graph.js
주어진 `edges` 를 `vertex`를 기준으로 저장하는 자료구조로 바꿔서 깊이우선탐색을 이용해 다음 링크된 꼭지점으로 계속 이동하여 `destinaion` 이 있으면 true 없으면 false를 반환하는 로직으로 접근했는데 maximum call stack error 가 나서 디버깅 중입니다...
- 시간 복잡도 : O(N + M)
- 공간 복잡도 : O(N + M)
깊이우선 탐색을 할때 destination 인지 아닌지에 대한 체크만 해서 destination이 아예 없는 순환 그래프 일때 탐색을 종료시키는 조건이 없어 콜스택 에러가 났었네요.
다만 생각해보니 이 문제는 DFS 보단 BFS 가 적절했던 문제같습니다.
인접한 꼭짓점들 부터 조사를 해야 가까이 있으면 결과가 빨리 나와서 시간상의 이점이 있으니까요.
BFS를 사용한 코드로 리팩토링 했습니다.
=> [2022.12.20] 길지문

problems/[221215] 1328. Break a Palindrome.js, problems/[221220] 1971. Find if Path Exists in Graph.js
저는 트리를 만들어서 조회하는 방향으로 해보려했는데 시간안에 트리를 만드는 함수를 완료하지 못했어요. 접근 방법이 잘못된 것 같은데 조금 더 업그레이드 시켜 보겠습니다! 
리뷰는 조언만 해주셔도 감사합니다☺️
- 시간 복잡도 : 오늘 하려 했던 방법은 On2
- 공간 복잡도 :
형우님 오늘 풀이 개선해보았습니다.
늦게 업데이트해서 죄송해요~ 시간이 넘 오래걸렸네요😭
DFS, BFS 이것들 언젠가는 공부해야지 하면서 안했는데 오늘 조금이나마 공부해서 좋았어요.
트리부분을 먼저 봤는데 제가 작성한 트리 로직도 정말 이상하게 작성했더라구요. 
bi 방향 그래프라길래 두갈래 밖에 없는거면 트리로 접근해도 될 것 같다 생각했는데, 개념 정립이 안되어있어서 잘못된 선택을 했던 것 같아요!
업데이트한 방법을 설명 드리면.. edges에 나와있는 vertex 2개를 key로 설정하고 value는 배열을 가지는 그래프를 만들어주었어요.
같은 vertex라면 값이 배열이니 push로 추가해주었어요.
왠지 여기까지만 말해도 형우님 촉이 오셨을 것 같은...!! 
(오늘 문제의 자료형은 number였지만 저는 문자로 다 바꿔주었네요.)
그림이 잘 나와있어 가져와봤어요.
이런 식으로 만들어주고
탐색하기 위한 재귀함수를 만들어주었어요.
그래프는 시작점을 지정해주어야 하니, 시작점인 source와 끝 부분인 destination을 지정해주고, 
이미 탐색한 것을 또 …
=> [2022.12.20] 임현정

problems/[221217] 88. Merge Sorted Array.js, problems/[221220] 1971. Find if Path Exists in Graph.js
안녕하세요~! 오늘 문제 통과하지 못했습니다 😞 
요즘 알고리즘 강의를 듣고 있는데 그래프 탐색 알고리즘에서 인접한 접점들을 먼저 조사하기 위해 큐를 사용해서 문제를 풀어보려고 시도했습니다!
다만 본 문제는 경로 자체를 찾는게 아니라 경로가 존재하는지 여부를 찾는 것이어서 애초에 접근을 달리 했어야 할 것 같은데, 뭔가 배운거를 시도(?)해보고자 하는 마음에 처음에 방향 설정이 잘못된 것 같습니다 ㅎㅎ
문제 마저 풀어본 후에 내용 더 보완하도록 하겠습니다 리뷰는 먼저 부탁드릴께요! 오늘 하루도 화이팅입니다~~ 🔥 
- 시간 복잡도 :
- 공간 복잡도 :
- DFS, BFS 사용 케이스에 대한 정리
=> [2022.12.20] 안형우

problems/[221220] 1971. Find if Path Exists in Graph.js
(*PR이 머지되어버려서 다시 올립니다~! 아무나 approve 좀 부탁드려요 ㅎㅎ)
그래프 문제에서는 보통 최단거리를 구하는게 많은데 본 문제는 "경로가 있는지 없는지"를 따지게 되므로, `source`로 부터 너비 우선 탐색을 통해 목적지를 찾는 것이 더 좋지 않을까 생각하고 적용해보았습니다. 탐색 순서는 아래와 같습니다.
1. enqueue start vertex
- visited set에 현재 vertex 추가
2. first dequeue
- 현재 vertex와 인접한(edge가 존재하는) vertices를 enqueue
- enqueue된 vertices는 visited set에 추가
3. dequeue
1. dequeue되는 vertex의 인접 vertices를 순회하며 각각이 visited set에 존재하는지 확인
2. 방문한 적 없는 vertices를 enqueue
3. queue가 전부 비워질 때까지 반복
4. 탐색 과정에서 현재 vertex와 `destination`이 일치할 경우 `true` 반환
현정님이 풀이해주신 내용이 아주 좋은 참고가 되었습니다 감사해요 👍🏽 보고나니까 강의가 더 이해가 잘 되더라구요 ㅎㅎ
사실 처음에는 현정님이 그래프를 인접 리스트로 표현해주셔서 저는 공부삼아 인접 행렬로 표현하여 구현했었는데, vscode나 개발자 도구에서는 실행이 되는데 리트코드에서는 특정 케이스에서 out of …
=> [2022.12.20] 안형우(graph, BFS 학습 후 다시 풀이)

problems/[22.12.22] 1. Two Sum.js, problems/[221227] 921. Minimum Add to Make Parentheses Valid.js
stack이라는 배열을 만들어주고 괄호 문자열을 앞부분부터 순회하는 걸 이용해 stack에 쌓아주는 방법을 택했습니다.
stack에 끝과 문자열 앞의 합이 "()"인 경우 스택에서 제거해주고, 아닐 경우 계속 stack에 쌓아갑니다. 
순회가 끝나면 stack의 길이를 리턴합니다.
- 공간 복잡도 : 제가 설정한 stack의 타입이 array이고 인자로 받은 s의 길이에 따라 stack의 길이가 달라질 수 있음으로 O(n)입니다.
=> [2022.12.27] 임현정

problems/[221227] 921. Minimum Add to Make Parentheses Valid.js, problems/[221229] 1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit.js
🙏🙏🙏
은혜님 혹시 리뷰 안하셨다면 추가 학습부분만 봐주세요. 처음에 풀었던 부분은 볼 만한 가치가 없어보여서.. 
다시 풀어보았는데 리뷰하고 계실까봐 다시 커밋하지는 못했어요.
<details>
<summary>처음 풀이</summary>
아 풀지 못했어요ㅠ 빨리 풀고 나가려 했는데 2시간동안 풀었네요ㅎㅎ 후..
완성되지 않은 함수라서 제 코드로 리뷰.. 하시기 보다는 조언 부탁 드립니다.. 보시기 힘들 거에요😢
while로 모두 순회해서 푼 방법은 시간초과로 실패했고 지금 올라간 방법에서 안되는 이유는 저 while문 안에서
```js
if (maximum - minimum <= limit) {
return copyArr.length;
}
```
이 조건을 만족하면 return하게 되어있는데 잘못되어있어요.
처음에 만들었던 재귀함수는
```js
(8) [4, 2, 2, 2, 4, 4, 2, 2] 'pop'
common-libs.6655d0e46.js:24 (7) [4, 2, 2, 2, 4, 4, 2] 'pop'
common-libs.6655d0e46.js:24 (6) [4, 2, 2, 2, 4, 4] 'pop'
common-libs.6655d0e46.js:24 (5) [4, 2, 2, 2, 4] 'pop'
common-libs.6655d0e46.js:24 (4) [4, 2, 2, 2] 'pop' …
```
=> [2022.12.29] 임현정

problems/[221229] 1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit.js, problems/[230103] 141. Linked List Cycle.js
릿코드 링크리스트에 적응이 필요할 것 같아요.. (ㅋㅋ)
head에 영향가지 않게 복사하고 싶었는데 링크리스트 구조가 어떤 식으로 되어있는지 모르겠어서 못했어요.
temp에 head를 복사하고 temp를 순회할 때 마다 visited라는 속성을 하나 추가해줬어요. cycle이 없으면 순회하지 않으니 while문을 빠져나와 false를 리턴하게 해주었습니다.
=> [2023.01.03] 임현정

problems/[221229] 1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit.js, problems/[230103] 141. Linked List Cycle.js
이미 다녀간 노드에 기록을 남기는 방식으로 해결하였습니다.
`node`를 순회하면서, `node`에 `visited`라는 프로퍼티를 추가해 순회해나가게됩니다.
순회하는 도중 `visited`라는 프로퍼티가 노드에 있는 경우, 사이클이 있는 경우므로 `true`를 반환합니다.
마지막 노드까지(`next`가 `null`일 때까지) `visited`가 없는 경우, `false`를 반환합니다.
- 공간 복잡도 : O(n). 연결리스트의 길이만큼 공간을 추가로 쓰게 되므로.
=> [2023.01.03] 공재혁

problems/[221227] 921. Minimum Add to Make Parentheses Valid.js, problems/[230103] 141. Linked List Cycle.js
오늘 문제는 이해를 제대로 못하다가... 막판에 풀긴했는데 통과되지 않는 케이스가 있네요 😞 
문제가 어떻게 테스트 되는건지 이해가 안가서 한참 헤메다가, 이미 거쳐갔던 노드를 다시 방문하면 안되는 것으로 판단해서 Set객체를 만들어 방문했던 노드의 `val` 값을 넣어줬습니다. 그런데 실행시켜보니 중복노드가 이미 있는 경우가 있더라구요..
정리하자면 주어진 케이스 내에 중복된 `val`값을 가진 노드가 이미 있건없건 상관 없이, `tail` 위치에 노드가 새로 추가될 때 추가되는 노드의 `val`값이 기존에 있던 값이고, 그 `next`값도 기존 노드와 같은 `next`값을 가지고 있으면, 즉 추가되는 노드의 `val`과 `next`가 모두 일치하는 기존노드가 있으면  안되는 것으로 이해했습니다...맞을까요? ㅎㅎ 확신이 없네요 도움 말씀 구합니다 😿 
+@
완전 바보같았군요...?? 일단은 `visitedSet`에 각 노드의 `val`값이 아닌 노드 자체를 넣는 방법으로 해결했습니다!
다만 공간복잡도가 최악이라 다른 풀이법을 고민해보아야겠습니다 ㅎㅎ
- 공간복잡도 개선해보기
=> [2023.01.03] 안형우

problems/[230103] 141. Linked List Cycle.js, problems/[230105] 82. Remove Duplicates from Sorted List II.js
안녕하세요~! 오늘 문제는 풀긴 했는데, 아직 연결리스트의 best practice들에 대한 공부가 안되어서..맞게 풀었는지 잘 모르겠네요.
직관적으로 봤을때는 분기처리도 너무 많고 정신없어서 잘 짜여진 로직이라고 보기 어려운 것 같습니다.
일단 풀이를 말씀드리자면,
1. 변수선언
- `root`를 별도로 선언한 이유는 매개변수를 수정하는 로직을 피하기 위함이었는데, 생각해보니 `root`든 `head`든 같은 데이터를 가리키기 때문에 불필요한 공간낭비라는 생각도 들긴합니다.. 이 부분 의견 부탁드려요!
- 나머지는 현재 노드를 기준으로 이전과 이후 노드를 저장했고, 중복 노드를 모두 지운후에 마지막으로 현재 가리키고있는 노드(중복노드 중 하나였던) 까지 삭제하기 위해서 별도의 `isDuplicatedNode`라는 플래그를 세워두었습니다
2. `while`문
- 기본적으로 `prevNode`(이하 p), `currentNode`(이하 c), `nextNode` (이하 n)를 계속 확인해가며 순회합니다
- p와 c의 `val`이 같다면(즉 중복 노드의 연속됨이 시작되면) 현재 노드의 포인터를 다음다음 노드(편의상 nn)를 가리키도록 하고(첫 번째 중복노드 삭제), `nextNode`에 이를(nn) 저장합니다. 그리고 플래그를 `true`로 바꾼 후 반복문을 탈출합니다. 이후 중복노드가 연속되는 동안은 이 과정이 계속 반복됩니다.
- c에 저장된 노드를 제외한 현재 반복중인 중복노드가 모두 제거되면, 플래그가 아직 `true`인 상태로 다음 조건문으로 넘어가게됩니다. 그런데 문제의 요구사항은 반복되는 노드를 …
=> [2023.01.05] 안형우

problems/[230103] 141. Linked List Cycle.js, problems/[230105] 82. Remove Duplicates from Sorted List II.js
`nodeHistory`라는 Map을 만들었습니다. 연결 리스트를 끝까지 순회해 값이 얼마나 나오게 되는 지 기록하게 됩니다.
그 후, 다시 처음부터 연결리스트를 순회해 `nodeHistory`의 빈도가 1인 노드만을 연결해 반환하도록 했습니다.
'이거 효율적이지 못한데..'라고 계속 되뇌이면서도 마땅한 방법이 떠오르지 않아 그냥 풀었고
결국 수행 시간이 5%가 떴습니다.. 주르륵.......
이 후에 좀 더 개선해보겠습니다...!
한 번 더 풀었습니당..
사실 문제를 풀고, 정렬이 되어있는 리스트 라는 것을 알게 되었습니다...
현재 노드(`currentNode`)의 값을 변수에 넣고, 다음 노드의 값이 다를 때까지 순회를 하게 됩니다.
중복이 있는 노드는 건너뛰게되는 셈입니다.
중복이 아닌 노드는 `resultHead`에 기록 되고, `resultHead`의 `next`값에 계속 기록되게 하였습니다.
시간은 40%로 많은 개선이 되었습니다. 감사합니다...
=> [2023.01.05] 공재혁

problems/[221229] 1438. Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit.js, problems/[230105] 82. Remove Duplicates from Sorted List II.js
주어진 Linked list를 돌며, prev / curr 값을 관리했습니다.
1. prev !== curr && duplicate !== prev 인 경우
: 새로운 linked list에 노드를 추가하고, prev와 curr을 하나씩 앞 노드로 이동합니다.
2. prev === curr 인 경우
: duplicate에 prev 값을 저장합니다.
=> [2023.01.05] 사공은혜 

problems/[221213] 11. Container With Most Water.js
**제가 생각한 풀이**
1번 head의 length 만큼 순회한다.
2번 파라미터로 받은 head.val === head.next 라면
3번 head.val 삭제하고
4번 head.next도 중복되니깐 삭제해야 하니 next 도 삭제해야 함을 가리키는 변수 설정해서 true 로 설정
5번 head === head.next로 설정 후 다시 2번으로 돌아간다
6번 2번에서 head.val !== head.next 인데 4번에서 설정한 변수가 true라면 
- head.val 삭제하고 
- head = head.next로 설정
- 중복을 나타내는 변수 다시 false로 설정
7번 2번에서 head.val !== head.next 인데 중복인지 아닌지 나타내는 변수가 false라면 
- head.val 삭제하지 않고 
- head = head.next로 설정
**잘 안됐던 부분**
1. 파라미터로 받은 head를 가지고 조작하기 보다는 얘를 다른 변수에다가 복사해서 그 변수를 사용해야할 것 같은데 초기에 어떻게 설정해야할지 잘 모르겠습니다.
2. head를 복사해서 복사한 값을 가지고 있는 변수를 사용한다고 가정한다고 해도 하나의 변수면 되는지 결국 반환되는 result에 관한 변수를 하나 더 설정해줘야 하는지 어떤 변 설정해줘야 하는지 잘 모르겠습니다.
- 시간 복잡도 : 
- 공간 복잡도 :
다른 분들 것 + 정답 보고 제가 오늘 풀이 했던 …
=> [23.01.05] 한아름

problems/[230105] 82. Remove Duplicates from Sorted List II.js, problems/[230110] 54. Spiral Matrix.js
방향을 크게 4가지로 잡아 풀었습니다.
(1) rightDirection
: secondIndex가 오른쪽 끝에 닿을 때까지 이동하며 result에 push
오른쪽 끝에 닿으면, 오른쪽 끝 인덱스-- 하고 bottomDirection 시작
(2) bottomDirection
: firstIndex가 아래 끝에 닿을 때까지 이동하며 result에 push
아래 끝에 닿으면, 아래 끝 인덱스-- 하고 leftDirection 시작
(3) leftDirection
: secondIndex가 왼쪽 끝에 닿을 때까지 이동하며 result에 push
왼쪽 끝에 닿으면, 왼쪽 끝 인덱스++ 하고 topDirection 시작
(4) topDirection
: firstIndex가 윗쪽 끝에 닿을 때까지 이동하며 result에 push
윗쪽 끝에 닿으면, 윗쪽 끝 인덱스++ 하고 rightDirection 부터 다시 반복
result 배열 속의 총 갯수가 matrix 내 총 갯수와 일치할때까지 위 과정을 반복한 후, 결과 반환했습니다.
- 시간 복잡도 :
=> [2023.01.10] 사공은혜

problems/[230103] 141. Linked List Cycle.js, problems/[230110] 54. Spiral Matrix.js
왠일루 풀었네요.. 
저는 재귀함수를 이용해서 풀었습니다.
빙글빙글 돌면서 배열에 추가하게되는데 중간 부분은 새로운 matrix라고 생각하고 재귀에 넣어주었어요.
재귀 함수 안에서는 
1. matrix배열의 첫 번째 배열을 `shift()`하여 result 배열에 `push`해줍니다. 첫 번째 줄이 끝나면 오른쪽에서 밑으로 내려가야 하므로
2. 마지막 배열을 제외하고 중간 부분 배열들을 `pop()`하여 실제로 제거해주고 pop된 요소들을 `middleLastItems` 라는 배열에 순차적으로 push해줍니다. 
`middleLastItems` 배열 요소들을 result 배열에 push해줍니다.
3. matrix배열의 마지막 배열을 `pop()` 하고 reverse시켜 result 배열에 push해줍니다.
4. 마지막 배열을 제외하고 중간 부분 배열들을 `shift()`하여 실제로 제거해주고 shift된 요소들을  `middleFirstItems` 라는 배열에 순차적으로 push해주고 배열을 reverse합니다. reverse된 `middleFirstItems` 배열을 result 배열에 push 해줍니다.
5. matrix 안 배열에 아이템이 남아있다면 재귀함수를 실행합니다.
- 시간 복잡도 : O(n^2)
- 공간 복잡도 : O(n) 재귀함수라서 스택에 쌓여가기 때문에 O(n)이라고 생각했습니다.
=> [2023.01.10] 임현정

problems/[230105] 82. Remove Duplicates from Sorted List II.js, problems/[230110] 54. Spiral Matrix.js
아직 매트릭스는 저한테 너무 어려운 것 같습니다...
풀이는 x, y 좌표의 각각 최솟값, 최댓값을 정해서(xMin, xMax, yMin, yMax) while문을 돌게 하는 것입니다.
처음에는 x축의 끝까지, 그 다음에는 y축 끝까지, 그 다음은 x축 최솟값까지, 그 다음 또 y축의 최솟값까지...
while 문을 돈 다음은, 다음 방향으로 갈 수 있는 지 체크합니다. 그 다음 방향으로 갈 수 없는 경우 결과값을 return 하도록 했습니다.
그런데 while문 조건을 잘못설정한건지 좌표가 계속 이탈이 나는 것 같습니다..
결국 풀지 못했습니다.. ㅜㅅ ㅜ
- 시간 복잡도 :
- 공간 복잡도 :
=> [2023.01.10] 공재혁

problems/[230110] 54. Spiral Matrix.js, problems/[230112] 48. Rotate Image.js
못 풀었습니당.. 
첨 접근했을 때 잘못 접근한 것 같아요 
배열 4개 짜리는 통과되는데 배열 5개부터 time limit 걸렸어요 어디서 무한루프가 걸린 것 같은데 찾기가 쉽지않네용 흑흑
재혁님 어마무시한 코드가 나왔는데.. 다 확인하지 않아도 돼요.. 팁만 주셔도 괜찮습니다용..!!
- 시간 복잡도 :
- 공간 복잡도 :
```
const rotate = function(matrix) {
const tempMatrix = [...matrix];
const rotateCopyMatrix = [];
let index = 0;
while (tempMatrix[0].length) {
const tempMatrixItem = [];
for (let item of tempMatrix) {
tempMatrixItem.push(item.shift());
}
rotateCopyMatrix.push(tempMatrixItem.reverse());
}
while (index < matrix.length) {
for (let i = 0; i < matrix.length; i++) {
matrix[index][i] = rotateCopyMatrix[index][i];
}
index++;
}
};
```
재혁님 처음 코드가 너무 심했죠..? 미안해요..
=> [2023.01.12] 임현정

problems/[230110] 54. Spiral Matrix.js
오늘 문제 해결하지 못했습니다.
예를들어 n = 4인 matrix가 주어졌을 때,
0,0 -> 0,3 -> 3,3 -> 3,0
0,1 -> 1,3 -> 3,2 -> 2,0
0,2 -> 2,3 -> 3,1 -> 1,0
0,3 -> 3,3 -> 3,0 -> 0,0
으로 이동하는 것을 보고, 
두번째 인덱스가 다음 이동의 첫번째 인덱스가 되는 규칙을 적용해보려고 했는데... 실패했습니다.
좀 더 고민해보겠습니다. 조언이 있다면 부탁드려요!
(코드에 쓸만한게 없어서 빈 코드로 올리는 점 양해 부탁드립니다🙏)
- 시간 복잡도 :
- 공간 복잡도 :
=> [사공은혜] 2023.01.12

problems/[230105] 82. Remove Duplicates from Sorted List II.js, problems/[230112] 48. Rotate Image.js
안녕하세요~! 오늘 문제는 알고리즘이나 구조적인 측면없이... 무식한 방법으로 해결했습니다.
사실 처음에는 뭘 어떻게 해야하나 도저히 감이 안잡혀서 무작정 인덱스가 변경되어야 할 위치를 일일히 손으로 써봤는데요.
신기하게도 각 인덱스들이 변경될 때 일어나는 연산의 일정한 규칙이 있더라구요..!
이건 설명보다 그냥 보여드리는게 나을 것 같습니다 ㅎㅎ
일정한 규칙이 있는 것으로 봐서 아마도 뭔가 수학적인 원리가 있을 것 같은데.. 이는 추가적으로 조사해볼 예정입니다!
그래서 결과적으로 풀이한 방법은
1. 원본 배열 유지를 위해서 원소를 전부 빼내서 `tempMatrix`에 담아두고 (원본과 똑같은 형태로)
2. 위에서 발견된 규칙대로 다시 원본 배열에 넣어줬습니다
아주 심플하고...사실은 이게 되네 싶은.. 풀이였습니다 😞 
다른 분들 풀이랑 solution탭 보고 좀 더 프로그래밍 적인 풀이를 공부해봐야겠습니다~!
오늘 하루도 화이팅입니다 ㅎㅎ
- 시간 복잡도 : 이중 루프가 두번 있지만 상수는 무시되므로 O(n^2)
- 공간 복잡도 : 주어진 인자 `matrix` 만큼의 임시 배열이 필요하므로 O(n)
더 나은 풀이 고민해보기!
=> [2023.01.12] 안형우

problems/[230110] 54. Spiral Matrix.js, problems/[230112] 48. Rotate Image.js
이번 문제는 케이스 결과를 뚫어져라 쳐다본 끝에 성공할 수 있었습니다.
패턴을 보니 matrix가 한 번 뒤집힌 다음, 각 매트릭스의 첫번째 요소만 가져와서 배열을 만들면 첫 줄이 완성되었습니다.
그래서 그걸 이용해서 문제를 해결하였는데요.
첫 번째로 matrix를 뒤집어준 다음,
matrix의 처음 row부터 순회해 row 내의 index값(0, 1, 2...)가 본인의 column이 되어 그 자리의 요소와 바꿉니다.
바꾼 이유는, 덮어 씌우게되면 값을 잃게 되므로 값이 덮어씌워지지 않게 하기 위함입니다.
그리고 자리만 바꾸면 로직도 효율적으로 동작할 수 있습니다.
길이가 3인 매트릭스 일 때, 처음 행은 0 ~ 2 index 요소를 실행하고
두 번째 행은 1 ~ 2, 세 번째 행은 2만 해주면 되었습니다.
길이가 홀수일 때 중간 열의 중간 요소는 자기 자신과 바꾸게 됩니다.
별도로 이 부분은 최적화를 가져가지 않았는데, 경우의 수가 하나이기도 하고 동작도 잘 되어서 입니다.
=> [2023.01.12] 공재혁

problems/[230110] 54. Spiral Matrix.js, problems/[230117] 20. Valid Parentheses.js
오랜만에 다시 푸는 문제네요!
각 괄호마다 짝을 미리 지어줘서, 
괄호의 짝이 stack의 마지막 값과 일치하면 pop을, 일치하지 않으면 push하는 과정을 반복했습니다.
이번주도 화이팅입니다!!
=> [2023.01.17] 사공은혜

problems/[230112] 48. Rotate Image.js, problems/[230117] 20. Valid Parentheses.js
안녕하세요~! 오늘 문제 추억이 새록새록하네요...!
바코에서 이문제 나왔을때 막 `charCode` 이런거로 계산해서 풀어보다가 못풀었던 기억이 나는데...그래도 조금은 나아져서 다행인 것 같습니다 ㅎㅎ
오늘 풀이는 괄호문제에서 전형적으로 이용되는 스택을 사용해서 풀었습니다!
1. 기본적으로 여는 괄호일 경우 스택에 계속 push 해주고, 짝을 이루는 닫는 괄호가 나오면 스택에서 여는 괄호를 pop 해줍니다
2. 최종적으로 스택에 남은 괄호가 없어야 모든 괄호가 열고 닫혔다는 의미이므로 `true`를 반환하고, 아닐 경우 `false`를 반환합니다.
3. 연산 중간에 몇 예외케이스들은 바로 처리해줍니다
- 스택이 비어있는데 `paren`이 닫는 괄호일 경우, 이미 이 괄호를 여는 괄호가 없다는 의미이므로 바로 `false`를 반환합니다
- 스택의 마지막 괄호가 여는 괄호이고 현재 괄호가 닫는 괄호인데 짝이 맞지 않을 경우도 바로 `false` 를 반환합니다
저는 뜬금없이 감기가 들어서(집이랑 바코밖에 다닌데가 없는데...🫠) 요즘 못나가고있네요...다들 감기 조심하시구 컨디션관리 잘 하시구요!! 이번 한주도 모두들 화이팅입니다~!
- 시간 복잡도 : O(N)
- 공간 복잡도 : O(N)
=> [2023.01.17] 안형우

problems/[230117] 20. Valid Parentheses.js, problems/[230119] 21. Merge Two Sorted Lists.js, problems/[230124] 31. Next Permutation.js
- 원래는 두 개의 linked list를 돌면서 next를 조정해주는 식으로 하려고 했으나, 쉽지 않았습니다...
- 오늘 그냥 새 ListNode를 만들어 주는 방식으로 해결했습니다.
- 값이 작은 List의 현재 Node의 값을 새 ListNode의 값으로 추가해주는 방식을 사용했습니다.
- 이 후에 시간복잡도를 어떻게 올릴 수 있을까, 하다가 태욱님 코드를 보고 로직을 개선해봤습니다. 
- value가 undefined일 경우, 101이라는 값을 부여해, 남은 노드들을 다 가져올 수 있도록 했습니다.
-
=> [2022.01.20] 공재혁

problems/[230119] 21. Merge Two Sorted Lists.js
1. 새로운 빈 배열을 생성해서 파라미터로 받은 리스트 노드를 하나씩 넣어줬습니다.
2. 넣어주고 나서 `firstNodeList = firstNodeList.next` 처럼 head를 next 노드로 설정해주었습니다.
3. 배열에 들어간 노드들의 val 값으로 sort 해주었습니다.
4. for 구문을 돌면서 배열에 들어간 노드들의 next를 설정해줬습니다.
5. 배열의 제일 첫번째 요소를 반환해주었습니다.
- 시간 복잡도 : O(2N)
- 공간 복잡도 :
=> [23.01.21] 한아름

problems/[230112] 48. Rotate Image.js, problems/[230117] 20. Valid Parentheses.js, problems/[230124] 31. Next Permutation.js, problems/[230126] 32. Longest Valid Parentheses.js
저는 풀지 못하고 답안을 봤습니다.
이 풀이대로 풀고 주석으로 설명을 추가해 보았습니다.
설명에 나와있는 대로 풀면 공간 복잡도 O(1)인데 저는 새 배열을 할당해줘서 공간 복잡도 O(n)이라고 생각했습니다..!
아마 조건문 처리가 빠진 게 있어서 submit하면 통과되지는 않을 거에요..! 
좀 더 정리가 필요하네요.
- 시간 복잡도 : O(n2)
=> [2023.01.24] 임현정

problems/[230117] 20. Valid Parentheses.js, problems/[230126] 32. Longest Valid Parentheses.js
결국 실패했습니당 현정님...😭
( 가 나오는 횟수와 ) 가 나오는 횟수를 비교해서 count를 세 보려고 했는데
(() 와 같은 케이스에서 제대로 대응을 못했네요.... 흑
( 현재 코드 너무 지저분해서 이해하려 하시지 마세요. 저도 제가 뭘 한건지 잘 모르겠네요ㅋㅋㅋ쿠ㅜㅜㅜㅜ )
오랜만에 알고 스터디 참여했는데 아쉽군요..
낮 동안 조금 더 고민해보고 발전이 생긴다면 업데이트 하겠습니당
그럼 오늘도 좋은 하루 보내요 현정님💕
- 시간 복잡도 :
- 공간 복잡도 :
=> [2023.01.26] 사공은혜

problems/[230124] 31. Next Permutation.js
제출을 했으나, 기존 PR을 머지하지 않아서 다시 제출 합니다. 리뷰 간 양해 부탁드립니다...
원래는 inplace 방식으로 내부에서 위치를 바꾸거나 하는 방식으로 풀어보았으나,
엣지 케이스에서 대응할 방법이 마땅히 생각나지 않았습니다.
그래서 모든 경우의 수를 만들어서 다음 인덱스로 해결하려 했으나, 타임아웃으로 실패하였습니당..
어쨌든 inplace 방식으로 어떻게 해봐야 할 듯 합니다..
- 시간 복잡도 :
- 공간 복잡도 :
=> [2023.01.24] 공재혁

problems/[230119] 21. Merge Two Sorted Lists.js, problems/[230124] 31. Next Permutation.js
DFS 탐색을 통해서 구하려고 했으나, 다음 값을 찾았을 때 재귀를 빠져나오지 못해서 통과하지 못했습니다.
그래서 일단은 not in place 방식으로 풀었는데 릿코드 자체에서는 아예 이 방법을 막아버렸는지 통과하지 못하네요..
조금 더 공부해보겠습니다.
- 시간 복잡도 : O(n2)
- 공간 복잡도 : O(n2)
=> [2023.01.24] 한아름

problems/[230119] 21. Merge Two Sorted Lists.js, problems/[230124] 31. Next Permutation.js, problems/[230131] 179. Largest Number.js
1. 인자로 받은 배열에서 가장 큰 수가 0이면 early return 합니다.
2. 배열에서 인접한 요소들의 조합 중 더 큰 값이 먼저 오도록 sorting 해주었습니다.
- 이번 과정을 통해서 배운 것은
- 템플릿 리터럴을 사용하면 toString(), String() 메소드 사용 없이도 숫자를 문자열로 바꿀 수 있습니다.
- “24” - “14” 를 하면 자바스크립트 엔진은 산술 연산자 표현식을 평가하기 위해 산술 연산자의 피연산자 중에서 숫자 타입이 아닌 피연산자를 숫자 타입으로 암묵적 타입 변환합니다. 따라서 위와 같이 굳이 Number()로 감싸줄 필요 없습니다.
=> [23.02.03] 한아름

problems/[230124] 31. Next Permutation.js, problems/[230126] 32. Longest Valid Parentheses.js, problems/[230131] 179. Largest Number.js, problems/[230131] 32. Longest Valid Parentheses.js, problems/[230207] 7. Reverse Integer.js
숫자를 문자열로 접근해서 풀었습니다.
1. 숫자의 절대값을 문자열화 한 후, 
2. 뒤집은 문자열을 만들어주었습니다.
3. 문자열 비교를 통해 32비트 정수를 확인했습니다.
4. 강제 변환으로 숫자형으로 반환해주었습니다. x가 음수이면 이 때 -1을 곱해줍니다.
=> [2023.02.07] 공재혁

.gitignore, problems/[230131] 179. Largest Number.js, problems/[230131] 32. Longest Valid Parentheses.js, problems/[230207] 7. Reverse Integer.js
안녕하세요~! 오늘은 처음에 접근을 잘못해서 숫자를 이진수로 바꾸고 32비트에 해당하는지 확인하는등 삽질을 하다가... 결국 나중에는 주어진 32bit singed integer의 조건에 해당하는지만 확인하면 되는 것을 깨달아 생각보다 간단히 풀이가 되었습니다 ㅎㅎ 풀이 과정은 아래와 같습니다.
1. 우선 주어진 숫자를 뒤집어주는 `reverseInteger` 함수를 만들어서 인자로 주어진 'x'를 뒤집어 주었습니다.
2. 이후 주어진 32비트 정수의 조건에 해당하는지 확인 후, 조건 외라면 0을 반환하고 조건에 합당하면 뒤집힌 정수를 그대로 반환하도록 했습니다.
오늘 하루도 모두 화이팅입니다~!!
- 시간 복잡도 : 주어진 인자를 문자열로 변환 후 한 차례 순회하므로 O(N) 
- 공간 복잡도 : 주어진 인자를 문자열로 변환해 사용하기에 O(N)
=> [2023.02.07] 안형우

problems/[230207] 7. Reverse Integer.js, problems/[230209] 179. Largest Number.js
permutation 함수는 모든 경우의 수를 찾는 함수입니다.
1. 먼저 정렬해줍니다.
2. 반복문을 돌면서 맨 앞자리가 같은 수가 있을 때 keep이라는 배열에 넣어줍니다.
3. 앞자리가 다른 수가 나왔을 때 keep 배열에 permutation 함수를 실행해서 경우의 수를 찾은 다음 제일 큰 수를 result 문자에 넣어주고 keep을 비워줍니다.
4. 반복합니다.
만약에 앞자리가 같은 것들이 9개가 넘는 상황일 경우 경우의 수를 362880번 찾게되고... 12자리면.. 479001600번 찾게돼서 시간초과가 납니다..
이런 방식으로 풀었는데 시간초과가 나왔네요 흑흑 sort방법으로 푼 걸 찾아보겠습니다.
- 시간 복잡도 : O(n^2)
=> [2023.02.09] 임현정 179. Largest Number

problems/[230207] 7. Reverse Integer.js, problems/[230209] 179. Largest Number.js, problems/[230213] 41. First Missing Positive.js
sort 부분은 solution을 보고 해결했습니다....ㅜ
배열을 정렬해서 그 배열을 `join("")`한 문자열을 반환하는 원리로 해결하였습니다.
정렬을 하는 것이 관건이었는데, 각 자리 수를 계산하는 방식을 사용하다가 막혀있었는데요.
그냥 앞뒤로 붙인 문자와 뒤앞으로 붙인 문자를 비교해주기만 하면 되었었습니다...
이 후에는 "00" 케이스가 엣지케이스였는데요. [0, 0]이 들어오면 결과값으로 "0"이 반환되어야 하는데
"00"이 반환되게 됩니다. 그래서 앞에있는 0이 있을 때까지 제거해주었습니다.
- 시간 복잡도 :
- 공간 복잡도 :
=> [2023.02.09] 공재혁

problems/[230207] 7. Reverse Integer.js, problems/[230209] 179. Largest Number.js
1. 제일 첫번째 숫자를 기준으로 먼저 내림차순 정렬을 합니다.
2. 첫번째 숫자가 같은 경우의 기준을 어떻게 잡을 지 몰라서...우선은 나머지가 큰것을 크다고 판단하여 나머지가 크면 작은것과 위치를 변경하는 방법을 사용하였습니다. 
3. 첫번째 케이스는 통과하였으나 두번째 케이스에서 3, 30은 식안으로 들어오지만 34가 들어오지 않아 실패하였습니다.
- 시간 복잡도 : 🧐
- 공간 복잡도 :
다른 분들의 풀이법을 보니 sort 하나로 쉽게 끝내더라구요..정렬에 대해 공부를 더 해야할 것 같습니다!
=> [2022.02.09] 이상아

problems/[230207] 7. Reverse Integer.js, problems/[230209] 179. Largest Number.js
모든 경우의 수를 다 조합해서 push한다 (요소의 값을 비교해서 수학적으로 풀 순 없는 것인가)
이때 반복문의 횟수는 nums.length! 근데 factorial이 js에 없어 구현해야 돼, 중복을 거를 수 없어 제곱
또, 관건은 어떻게 배열 내 요소들을 움직일 것인가
모든 요소를 다 순회하면서 조합해 큰 수를 찾으려 했지만
일단 로직을 다 짜지 못했고, 지금 상태는 시간 초과 상태입니당.....
- 시간 복잡도 : 최악
- 공간 복잡도 :
=> [2023.02.09] 이세영

problems/[230207] 7. Reverse Integer.js, problems/[230213] 41. First Missing Positive.js
어제 40분 정도 + 오늘 20분 정도
1. 주어진 파라미터의 요소보다 하나 더 많게하여 `1`부터 연속되는 숫자의 배열을 만들어줬습니다.
2. `for`문 안에서 `sequence`의 요소를 파라미터의 배열이 포함하지 않으면 해당 `sequence`의 요소를 반환하도록 했습니다.
- 매우 긴 배열이 주어진 마지막 테스트 케이스를 시간 초과로 통과하지 못했습니다. 모든 요소를 검사하는 for문이 아니라, 다른 방법을 모색해봐야 할 것 같습니다.
- 공간 복잡도 :
=> [2023.02.14] 최송이

problems/[230213] 41. First Missing Positive.js, problems/[230216] 221. Maximal Square.js
시간을 측정하지 않았네용.. 어제 한 시간정도 풀다가 오늘 새로 40분 정도 풀었습니다.
어제 너무 안풀린 나머지 솔루션을 보았습니다.. ㅎㅎ;
다만 솔루션을 보고 이런 방식으로 풀 수 있구나!를 깨닫고 저만의 방법으로 풀어보았습니당..
각 배열을 순회하면서, 값이 1인 경우 0번 인덱스로, 2인 경우 1번 인덱스로 가게 합니다.
nums에 1, 2, 3, 4값이 있다면 순회가 완료되면 nums는 [1, 2, 3, 4...]와 같이 됩니다.
만약 하나라도 값이 없으면 1, 2, ...에서 끊기기 때문에 3을 쉽게 찾아낼 수 있습니다.
몇몇 엣지케이스가 있어 while문의 조건이 복잡해보이기는 하지만, 기본적으로는 값이 1인 요소를 1로 가게 하는 방식입니다.
변수 `moveNum`을 설정해주었는데, 이유는 한 번에 하나만 움직이는게  아니라 연쇄적으로 움직일 수 있도록 구현한 것입니다.
=> [2023.02.14] 공재혁

problems/[230216] 221. Maximal Square.js
1시간
각 열을 모두 순회해, 해당 열을 좌측 상단 0, 0 인덱스로 가지는 사각형이 되는 지 확인했습니다.
시간복잡도 면에 아주 좋지 않네요... 솔루션을 보고 더 나은 방법을 찾아보겠습니다.
- 시간 복잡도 :
- 공간 복잡도 :
=> [2023.02.16] 공재혁

problems/[230207] 7. Reverse Integer.js, problems/[230209] 179. Largest Number.js, problems/[230213] 41. First Missing Positive.js, problems/[230220] 73. Set Matrix Zeroes.js
약 10시간 하하하핳
로직을 처음에 잘못 생각했는지 엣지케이스들 처리하느라 시간도 많이 들고 if 처리도 많아졌습니다 은혜님
길고 지저분 하더라도 간만에 만나는거니 반가운 마음으로, 너그러이 봐주십숑😘
배열을 순회하며 음수인 요소를 삭제하고 싶었는데 그럼 O(N)으로 풀 수 없을 것 같아
배열의 요소가 양수냐 음수냐로 분기 처리했습니다.
- 음수 : continue (단, 배열의 요소가 1개거나 전부 음수라면 return 1)
- 양수 : index로 카운팅하며 1부터 요소가 순차적으로 채워져 있는지 확인. 
: 맞게 순회되고 있다면 continue
: 양수 값이 1부터 배열 끝까지 잘 채워져 있으면 return 배열 마지막 요소 + 1;
: 단, 양수 카운트 시작인데 1이 아니라면, return 1
: 맞게 순회되지 않는다면 return index값
- 시간 복잡도 : O(N)
=> [2023.02.15] 이세영

problems/[230209] 179. Largest Number.js, problems/[230216] 221. Maximal Square.js
2시간
완전탐색으로 접근했습니다.
처음에 1인것을 먼저 찾고, 1을 발견했을 때의 좌표값을 DFS함수에 넘겨줍니다.
DFS는 받은 좌표값을 기준으로 좌, 우, 위, 아래를 탐색하며 같은 1이 있는지를 탐색해서 같다면 1을 올리는 식으로 접근하였습니다.
접근은 했는데..일단 실패했습니다. 풀이법을 보니 DP로 아주 간단하게들 푸시더라구요.
그래서 DP로 익혀두긴 했지만..완전 탐색으로도 풀 수 있었을 것 같은데 아쉽네요..
- 시간 복잡도 :🧐
- 공간 복잡도 :
=> [2023.02.17] 이상아

problems/[230220] 73. Set Matrix Zeroes.js
엄.. 집중해서 한 것은 1~2시간...?
1. 매개변수의 길이 / 매개변수 각 요소의 길이를 각각 Y, X 인덱스 값으로 할당해서
값이 0인 곳의 X, Y 인덱스를 저장할 배열에 각각 push
2. 1에서 찾은 인덱스를 기준으로 매개변수의 해당하는 인덱스의 값을 0으로 재할당
하는 방법으로 풀어보았습니다. 샹아님~~~ 
- 시간 복잡도 : O(N²)
- 공간 복잡도 : O(N)
=> [20230220] 이세영

problems/[230216] 221. Maximal Square.js, problems/[230220] 73. Set Matrix Zeroes.js
매트릭스를 전부 탐색하면서 0인 좌표값을 position 배열에 담아둡니다.
position에 저장된 값을 행(x)과 열(y)로 나누어 해당 행과 열을 모두 0으로 바꾸는 로직을 사용하였습니다.
- 시간 복잡도 :
- 공간 복잡도 :
=> [2023.02.22] 이상아

problems/[230216] 221. Maximal Square.js, problems/[230220] 73. Set Matrix Zeroes.js
20분
각 셀을 돌면서, 0이 담긴 행 index와 열 index를 모두 담아주었습니다.
다시 각 셀을 돌면서 0이 담긴 index에 해당할 경우, 0으로 만들어주었습니다.
한 번의 순회로 끝내고 싶은데 쉽지 않네요... 솔루션을 보니 알 것도 같은데 풀기 쉽지 않습니당
=> [2023.02.20] 공재혁

problems/[230220] 73. Set Matrix Zeroes.js, problems/[230223] 632. Smallest Range Covering Elements from K Lists.js
1시간
문제에서 중요하게 생각했던 건 특정 범위 내에 `nums` 배열의 각 요소가 모두 포함되어야 한다는 것입니다.
그래서 각 `nums` 내의 배열에서 하나의 값들이 담긴 `currentNumbers` 배열을 만들어주었습니다. 초기값은 맨 마지막 인덱스로 해주었습니다.
그 다음 `currentNumbers`에서 가장 큰 값을 빼주고, `nums`에서 해당 인덱스의 배열의 맨 마지막 요소를 가져옵니다.
이렇게 하면 `currentNumbers` 배열은 모든 숫자를 하나씩 갖게되는 걸 유지할 수 있습니다.
바뀐 `currentNumbers` 배열의 range와 기존 range를 비교한 후, 더 작으면 `min`과 `max`를 바꾸어줍니다.
- 시간 복잡도 : O(mn) m은 nums의 길이, n은 nums 내 배열의 길이
=> [2023.02.23] 공재혁

problems/[230131] 179. Largest Number.js, problems/[230220] 73. Set Matrix Zeroes.js, problems/[230223] 632. Smallest Range Covering Elements from K Lists.js, problems/[230227] 108. Convert Sorted Array to Binary Search Tree.js
750ms짜리 30분
110ms짜리 3시간
원래 750ms짜리 풀이는
picker라는 배열을 nums의 길이만큼 만들어서 각 k마다의 진행도를 표시한 다음
nums[k]의 picker[k] 인덱스끼리의 값을 비교해서 최소값인 것을 인덱스 1씩 더 진행시켜가면서 smallest range를 찾아줬었습니다.
예를들면
list1 - [0, 2, 5] -> nums[0]
list2 - [3, 4, 12] -> nums[1]
list3 - [5, 9, 10] -> nums[2]
이렇게 주어졌을 때
picker의 초기값은 [0, 0, 0]입니다.
따라서 i를 nums의 length만큼 순회하면서 `nums[i][picker[i]]`를 비교해줍니다.
그중 최소값을 구해서 picker[i]를 +1 해줍니다(다음 인덱스로)
이 순회 동안 max값과 min값을 구해줍니다.
max값과 min값의 차이가 현재 smallest range와 비교해서 더 작으면 smallest range를 바꿔줍니다.
이걸 `nums[i][picker[i]]`값이 undefined가 될때까지 반복한 뒤 smallest range를 반환합니다.
이 방식의 문제점은 반복을 지나치게 많이 해야한다는 점입니다.
같은 값을 너무 많이 중복해서 순회하게 됩니다.
그래서 개선을 위해 도입한 방식에서는 heap 자료구조를 이용합니다.
최소값을 꺼내는 게 중요하기 때문에 min heap을 …
=> [2023.02.23] 박태욱

problems/[230223] 632. Smallest Range Covering Elements from K Lists.js, problems/[230227] 108. Convert Sorted Array to Binary Search Tree.js, problems/[230302] 101. Symmetric Tree.js
20분
말 그대로 BST를 새로 생성해주었습니다.
중간 인덱스(`pivotIndex`)를 찾아 root의 value값으로 반환해주었고
nums의 길이에 따라 자식 요소가 하나 이상이면 재귀로 새로운 노드를 만들어주었습니당.
early return으로 배열의 길이가 하나인 경우를 처리해주었습니다.
- 시간 복잡도 : 재귀라서 계산 어케하는 건지 모르겠네욥..
- 공간 복잡도 : O(n) - slice로 새로운 자식 배열 생성
=> [2023.02.27] 공재혁

problems/[230216] 221. Maximal Square.js, problems/[230220] 73. Set Matrix Zeroes.js, problems/[230227] 108. Convert Sorted Array to Binary Search Tree.js, problems/[230302] 101. Symmetric Tree.js
사실 기존에 풀었던 문제라.. 이번에 쉽게 제출할 수 있었던 것 같습니다 🤗
순서대로 정렬되어 있기 때문에 가장 중간부분을 root로 잡습니다.
root보다 작은 숫자를 left에 두고, root보다 큰 숫자를 right에 두는 방법으로 접근했습니다.
- 시간 복잡도 :🧐
- 공간 복잡도 :
=> [2023.02.27] 이상아

problems/[230227] 108. Convert Sorted Array to Binary Search Tree.js
15분
이미 정렬된 배열을 받습니다.
따라서 따로 정렬로직이 필요 없습니다.
배열을 반을 갈랐을 때 중앙의 요소로 node를 만듭니다.
해당 node의 left는 위 중앙 요소 기준으로 배열의 왼쪽의 중앙 요소로 만든 node입니다.
이를 코드로 표현해서 재귀시킵니다.
- 공간 복잡도 : stack에 각 left와 right가 쌓이기 때문에 이를 따로 변수로 선언하지 않고 바로 sortedArrayToBST의 인자로 넘겨주면 공간복잡도를 줄일 수 있습니다. 다만 좀 더 선언적인 코드를 위해 그대로 뒀습니다.
=> [2023.02.27] 박태욱

problems/[230207] 7. Reverse Integer.js, problems/[230216] 221. Maximal Square.js
1시간
안녕하세요! 오늘 문제는 제대로 손 못대보고 시간을 보내서 우선은 제출합니다.. 처음 계획은
1. 각 row에서 값이 1인 인덱스만 따로 모은다
2. 이렇게 만들어진 새 중첩배열에서 공통적으로 연속되는 인덱스를 계산해낸다
였는데.. 2번을 어떻게 풀어낼지 고민만 하다가 시간이 다 가버려서 공부가 더 필요할 것 같아 이만 제출합니다.. 추후 다시 풀이해보려고 합니다!
이번 한주도 고생 많으셨구 다음주도 화이팅입니다~!!
- 시간 복잡도 :
- 공간 복잡도 :
=> [2023.02.18] 안형우

problems/[230227] 108. Convert Sorted Array to Binary Search Tree.js, problems/[230302] 101. Symmetric Tree.js
35분
지그재그로 재귀합니다.
함수명은.. 그냥 재귀로 했습니다. solution함수 이름이 재귀 이름이면 좋을 것 같은데 그러면 함수명이 중복돼서 그냥 일단 재귀로 했는데 좋은 방법 있으면 추천해주세요.
조건문이 많고 지저분한데 우선 줄일 방법 생각안하고 그냥 올립니다..!
- 시간 복잡도 :  O(n)
- 공간 복잡도 : S(1) 재귀함수 선언을 제외하면 따로 공간을 추가로 쓰진 않는 것 같습니다.
=> [2023.03.02] 박태욱 101. Symmetric Tree

problems/[230302] 101. Symmetric Tree.js
1시간 20분
스택과 큐를 만들어서 풀었습니다.
큐는 BFS를 위해서 만들어주었습니다. 큐로 노드가 쌓이면서 BFS로 트리를 탐색합니당.
그리고 노드를 탐색하면서 stack에도 값들을 쌓아줍니다.
대칭인 경우면 stack의 끝 두 개의 값이 같을거니까 그 때 배열을 팝팝 시켜주었습니다 팝팝
다만 엣지케이스가 많이 나와서 좀 코드가 너저분해졌는데요..
위 케이스에서 가장 엣지케이스가 많이 나왔습니다.
자식 노드가 없을 경우, undefined 두 개가 stack에 쌓이는데요. 그럴경우 stack에서 지워져버려서 대칭이 아님에도 대칭이라고 판단해버리는 엣지 케이스가 있었습니다. 그래서 자식노드가 없는 경우는 따로 `false`라는 임의의 값을 넣어 처리하도록 했습니다.
다만 위의 경우를 처리하니 node가 root하나만 있는경우에 false가 담겨서 stack이 비워지지 않는 엣지 케이스도 발생했는데요.. 그 경우를 위한 early return도 추가했습니다..
생각보다 쉽지 않은 문제였네여...
=> [2023.03.02] 공재혁

problems/[230302] 101. Symmetric Tree.js
우선 root부터 비교해서 없으면 바로 true로 리턴 처리하였습니다.
그 다음은 왼쪽과 오른쪽으로 나누어서 재귀가 돌면서 비교하는 함수를 하나 만들었는데요
하나라도 없거나 값이 같지 않으면 false로 리턴하는 식으로 케이스를 하나하나 추가하다보니 조건문이 좀 많아진 것 같네요..
그리고 거울에 비친것과 같은 모양으로 비교를 해야하니 재귀를 돌릴 때 왼쪽과 오른쪽, 오른쪽과 왼쪽을 모두 비교하도록 하였습니다.
참고로 마지막 else false를 처음에는 추가하지 않았었는데, 추가해보니 메모리면에서 효율이 올라가서 추가해두었습니다.
감사합니다.
** 오늘 푼게 저번 문제에 추가되어져서 매개변수 이름을 좀 수정하였습니다. 내용은 동일합니다!!
- 시간 복잡도 : O(n)?
- 공간 복잡도 : O(n)?
=> [2022.03.02] 이상아

problems/[230213] 41. First Missing Positive.js, problems/[230216] 221. Maximal Square.js, problems/[230220] 73. Set Matrix Zeroes.js, problems/[230302] 101. Symmetric Tree.js
3시간
1. 왼쪽 트리 먼저 dfs 순회하면서 leftTreeValues 배열에 값들을 넣어줍니다. 이 값들을 reverse한 값은 오른쪽 트리를 (왼쪽 트리는 왼쪽에서 오른쪽 순서, 오른쪽 트리는 오른쪽에서 왼쪽 순서로 순회합니다.) 순회한 값과 같아집니다.
3. 오른쪽 트리를 순회하면서 reverse한 leftTreeValues배열을 pop한 값과 순회하는 값을 비교합니다. 
4. 비교해서 같지않으면 바로 재귀를 종료합니다. (값이 null인 경우 예외값으로 101을 넣어줬습니다.)
좀 더 효율적으로 풀 수 있을 것 같아 계속 잡고 있었는데 안되네용.. 아름님 저 늦게올려서 리뷰 안해주셔도 됩니다융
- 시간 복잡도 : On
- 공간 복잡도 : On
=> [2023.03.04] 임현정

problems/[230302] 101. Symmetric Tree.js, problems/[230306] 74. Search a 2D Matrix.js
1시간 5분
half : 매트릭스 길이의 반
halfMatrix : half 변수를 이용해서 매트릭스를 반으로 자르고, target 범위에 있는 배열을 할당한 변수입니다.
while문으로 계속 half의 범위를 half 반으로 좁혀가면서 반복합니다. halfMatrix도 위와 같은 작업을 반복합니다. halfMatrix 배열의 길이가 1이 될때까지 반복합니다.
halfMatrix 배열의 길이가 1이 됐을 때 그 배열 안에 target이 있는지 체크한 값을 리턴합니다.
- 시간 복잡도 : O(log(m * n))
- while안의 메서드땜시 log가 아닐 것 같구먼유?
- 공간 복잡도 : On
=> [2023.03.06] 임현정 74. Search a 2D Matrix

problems/[230302] 101. Symmetric Tree.js, problems/[230306] 74. Search a 2D Matrix.js, problems/[230309] 104. Maximum Depth of Binary Tree.js
15분
매트릭스 row의 가장 첫 인덱스가 해당 row의 가장 작은 수입니다.
따라서 target보다 작은 가장 마지막 row를 찾아가서 배열에 값이 포함되어있는 지 확인합니다.
includes로 이를 확인했는데, for문을 쓰는게 더 빨라서 방식을 바꾸었습니다.
- 시간 복잡도 : O(m + n)
=> [2023.03.08] 공재혁 74. Search a 2D Matrix

problems/[230302] 101. Symmetric Tree.js, problems/[230306] 74. Search a 2D Matrix.js
1시간 30분
보통 행렬을 풀 때 이중 for문을 많이 사용하게 되는데 이 경우 n2로 풀면 안되는 문제라 
mid로 중간을 잡고 target과 비교하여 작으면 count를 올리고 크면 count를 내리는 방법이 떠올라 적용했습니다.
숫자는 오름차순으로 정렬되어 있으므로 첫 행에서 제일 마지막 숫자를 기준으로 잡고,
target 보다 작으면 그 다음 행에 큰 수로 넘어가서 비교해야하니 col을 늘려줬고,
target 보다 크면 앞으로 이동하여 작은 숫자들과 비교해야하니 row를 줄여줬습니다.
사실 몇몇 테스트가 통과되지 않아서..집단 지성의 힘을 조금 빌렸습니다.
while문에서 조건 처리해줄 때 row는 총 길이가 넘지 않도록, col은 0보다는 크도록 미리 지정해주지 않아서
시간제한에 걸렸었는데, 조건 지정해주고 모두 통과할 수 있었습니다.
감사합니다.
- 시간 복잡도 : 🧐
- 공간 복잡도 : 🧐
=> [2023.03.06] 이상아

problems/[230306] 74. Search a 2D Matrix.js, problems/[230309] 104. Maximum Depth of Binary Tree.js
1시간
처음에는 왼쪽과 오른쪽을 재귀를 돌면서 count를 이용하는 방식을 사용한후 count를 리턴하는 방식으로 접근하였습니다.
하지만 재귀가 리턴하는 값이 무엇인지에 대한 이해가 부족했어서인지 통과가 되지 않아 병석님의 도움을 조금 얻었습니다.
값이 없으면 0을 리턴하고 값이 있으면 +1을 해서 depth를 구하는 방식을 사용하였습니다.
왼쪽과 오른쪽에 대한 depth를 구한 뒤 더 큰수를 리턴하는 방식을 사용하였습니다.
- 시간 복잡도 :🧐
- 공간 복잡도 :🧐
=> [2023.03.09] 이상아

problems/[230309] 104. Maximum Depth of Binary Tree.js
15분
재귀를 이용해서 풀었습니다.
DFS 탐색을 통해서 left와 right중 더 깊은 깊이를 가진 노드를 반환하는 방식입니다.
=> [2023.03.09] 공재혁 104. Maximum Depth of Binary Tree
